### ISSUE TITLE
Footer enhancement

### ISSUE THREAD

**Issue by KavyaBS123** [NiranjanKumar001/iPhone-16-Pro-Clone#13]
Hey @NiranjanKumar001 go to top button can be added for better UX.

**Comment by NiranjanKumar001** [comment]
Great idea ,but as we are working on cloning a site ,we would try to make it alike and i don't think its there on official site. So as You are looking for some thing which is easier. i am makin it  a footer enhancement issue, you will have to just make the footer which is just some code with alot of texts . i am assigning you this if you want you can star the repo and proceed .

**Comment by KavyaBS123** [comment]
Hey Niranjan Kumar
I have raised the pr, can you please check out.
