### ISSUE TITLE
FIXING both buy button color

### ISSUE THREAD

**Issue by NiranjanKumar001** [NiranjanKumar001/iPhone-16-Pro-Clone#47]
there are two buy button , one in the hero section and other in the the floating navbar .Use color picker or anything you want fix the color.
![Screenshot 2024-10-24 130040](https://github.com/user-attachments/assets/c5169cf4-4bea-4a6e-a255-c60b7fa3387b)
![Screenshot 2024-10-24 130047](https://github.com/user-attachments/assets/318e318f-6254-4994-ba5f-5e822c64e3f4)
ORIGINAL !!
![Screenshot 2024-10-24 130035](https://github.com/user-attachments/assets/ebc193cd-dcc9-49e4-99ec-11268288146f)
![Screenshot 2024-10-24 130056](https://github.com/user-attachments/assets/5745b894-89d1-438d-a221-c6e7beb67f1b)
what we have!!

**Comment by parteekxo** [comment]
sure do you want any specific color?

**Comment by kartik-212004** [comment]
can i do this issue
?

**Comment by parteekxo** [comment]
> can i do this issue ?

finished already bro..

**Comment by kartik-212004** [comment]
😭😭😭
